name: resturantapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  lottie: ^2.2.0
  flutter_bloc:
  dio: ^5.0.0
  image_picker:
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  conditional_builder_null_safety:
  responsive_framework: ^0.2.0
  tbib_splash_screen: ^1.0.0
  pretty_dio_logger: ^1.3.1
  loading_animation_widget: ^1.2.0+4
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg:
  expandable_text: ^2.3.0
  animated_splash_screen: ^1.3.0
  flutter_slidable: ^3.0.0
  cached_network_image: ^3.3.0
  favorite_button: ^0.0.4
  easy_stepper: ^0.8.1
  dotted_line: ^3.2.2
  flutter_staggered_grid_view: ^0.7.0
  modal_progress_hud_nsn: ^0.4.0
  carousel_slider:





  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF


